[package]
name = "dash89"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
nt_client = "0.2.0"
ratatui = "0.29.0"
tokio = "1.44.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
user_dirs = "0.2.0"
